### ISSUE TITLE
code won't compile

### ISSUE THREAD

**Issue by yuan0623** [Pouya-moh/urdf-to-kdl#1]
Hi, I have downloaded your repo and I try to compile it, but I run into an error.
Here is what I have done:
In the `urdf-to-kdl/`, I run `mkdir build`
`cd build`, `cmake ..` (I also have tried `cmake -DBUILD_TEST=ON ..`), and then `make`. The error is here: 
/home/yuan/Desktop/urdf-to-kdl/src/kdl_parser.cpp:75:13: error: ‘KDL::Joint kdl_parser::toKdl’ redeclared as different kind of symbol
 Joint toKdl(boost::shared_ptr<urdf::Joint> jnt)
             ^~~~~
/home/yuan/Desktop/urdf-to-kdl/src/kdl_parser.cpp:69:7: note: previous declaration ‘KDL::Frame kdl_parser::toKdl(urdf::Pose)’
 Frame toKdl(urdf::Pose p)
       ^~~~~
/home/yuan/Desktop/urdf-to-kdl/src/kdl_parser.cpp:75:13: error: ‘boost’ has not been declared
 Joint toKdl(boost::shared_ptr<urdf::Joint> jnt)
             ^~~~~
/home/yuan/Desktop/urdf-to-kdl/src/kdl_parser.cpp:75:42: error: expected primary-expression before ‘>’ token
 Joint toKdl(boost::shared_ptr<urdf::Joint> jnt)
                                          ^
/home/yuan/Desktop/urdf-to-kdl/src/kdl_parser.cpp:75:44: error: ‘jnt’ was not declared in this scope
 Joint toKdl(boost::shared_ptr<urdf::Joint> jnt)
                                            ^~~
/home/yuan/Desktop/urdf-to-kdl/src/kdl_parser.cpp:75:44: note: suggested alternative: ‘jnl’
 Joint toKdl(boost::shared_ptr<urdf::Joint> jnt)
                                            ^~~
                                            jnl
/home/yuan/Desktop/urdf-to-kdl/src/kdl_parser.cpp:106:24: error: ‘KDL::RigidBodyInertia kdl_parser::toKdl’ redeclared as different kind of symbol
 RigidBodyInertia toKdl(boost::shared_ptr<urdf::Inertial> i)
                        ^~~~~
/home/yuan/Desktop/urdf-to-kdl/src/kdl_parser.cpp:69:7: note: previous declaration ‘KDL::Frame kdl_parser::toKdl(urdf::Pose)’
 Frame toKdl(urdf::Pose p)
       ^~~~~
/home/yuan/Desktop/urdf-to-kdl/src/kdl_parser.cpp:106:24: error: ‘boost’ has not been declared
 RigidBodyInertia toKdl(boost::shared_ptr<urdf::Inertial> i)
                        ^~~~~
/home/yuan/Desktop/urdf-to-kdl/src/kdl_parser.cpp:106:56: error: expected primary-expression before ‘>’ token
 RigidBodyInertia toKdl(boost::shared_ptr<urdf::Inertial> i)
                                                        ^
/home/yuan/Desktop/urdf-to-kdl/src/kdl_parser.cpp:106:58: error: ‘i’ was not declared in this scope
 RigidBodyInertia toKdl(boost::shared_ptr<urdf::Inertial> i)
                                                          ^
/home/yuan/Desktop/urdf-to-kdl/src/kdl_parser.cpp:137:24: error: ‘boost’ has not been declared
 bool addChildrenToTree(boost::shared_ptr<const urdf::Link> root, Tree& tree)
                        ^~~~~
/home/yuan/Desktop/urdf-to-kdl/src/kdl_parser.cpp:137:42: error: expected primary-expression before ‘const’
 bool addChildrenToTree(boost::shared_ptr<const urdf::Link> root, Tree& tree)
                                          ^~~~~
/home/yuan/Desktop/urdf-to-kdl/src/kdl_parser.cpp:137:70: error: expected primary-expression before ‘&’ token
 bool addChildrenToTree(boost::shared_ptr<const urdf::Link> root, Tree& tree)
                                                                      ^
/home/yuan/Desktop/urdf-to-kdl/src/kdl_parser.cpp:137:72: error: ‘tree’ was not declared in this scope
 bool addChildrenToTree(boost::shared_ptr<const urdf::Link> root, Tree& tree)
                                                                        ^~~~
/home/yuan/Desktop/urdf-to-kdl/src/kdl_parser.cpp:137:72: note: suggested alternative: ‘free’
 bool addChildrenToTree(boost::shared_ptr<const urdf::Link> root, Tree& tree)
                                                                        ^~~~
                                                                        free
/home/yuan/Desktop/urdf-to-kdl/src/kdl_parser.cpp:137:76: error: expression list treated as compound expression in initializer [-fpermissive]
 bool addChildrenToTree(boost::shared_ptr<const urdf::Link> root, Tree& tree)
                                                                            ^
/home/yuan/Desktop/urdf-to-kdl/src/kdl_parser.cpp: In function ‘bool kdl_parser::treeFromUrdfModel(const urdf::ModelInterface&, KDL::Tree&)’:
/home/yuan/Desktop/urdf-to-kdl/src/kdl_parser.cpp:214:75: error: ‘kdl_parser::addChildrenToTree’ cannot be used as a function
         if (!addChildrenToTree(robot_model.getRoot()->child_links[i], tree))
                                                                           ^
CMakeFiles/KDL_Parser.dir/build.make:82: recipe for target 'CMakeFiles/KDL_Parser.dir/src/kdl_parser.cpp.o' failed
make[2]: *** [CMakeFiles/KDL_Parser.dir/src/kdl_parser.cpp.o] Error 1
CMakeFiles/Makefile2:95: recipe for target 'CMakeFiles/KDL_Parser.dir/all' failed
make[1]: *** [CMakeFiles/KDL_Parser.dir/all] Error 2
Makefile:103: recipe for target 'all' failed
make: *** [all] Error 2

Does this package require any additional library? Do you know how to resolve it?

Best
Yuan

**Comment by Pouya-moh** [comment]
Hi.

I think the problem is related here and everything else is just C++ compiler going crazy as usual:

```
/home/yuan/Desktop/urdf-to-kdl/src/kdl_parser.cpp:75:13: error: ‘KDL::Joint kdl_parser::toKdl’ redeclared as different kind of symbol
```

This repo is a bit old so there might be change in KDL or Boost API. Which version of boost and KDL are you on?

> Does this package require any additional library? Do you know how to resolve it?

The dependencies by looking at CMakeLists.txt seems to be KDL, Boost, Urdfdom and Tinyxml. I would check KDL or Urdfdom first. Let me know

Bests,
P.

**Comment by yuan0623** [comment]
Hi Pouya,

Thanks for your reply. 
If `/home/yuan/Desktop/urdf-to-kdl/src/kdl_parser.cpp:75:13: error: ‘KDL::Joint kdl_parser::toKdl’ redeclared as different kind of symbol` is the issue, then how am I supposed to resolve it? Do you have any idea? 
The KDL version I'm using is 1.4.1. Not sure about the version of the boost.
By the way, do you know other tools that can parse urdf to KDL without using ROS?

Best
Yuan

**Comment by lepalom** [comment]
The problem here is that urdfdom changes from boost::shared_ptr to std::shared_ptr so this old piece fails with this. Change:

-  boost::shared_ptr to std::shared_ptr
-  drop in CMakeList.txt in the include_directory the SYSTEM keyword

and it should work.
