### ISSUE TITLE
How to obtain joint info from urdf which will be used to add segment to KDL chain

### ISSUE THREAD

**Issue by mink007** [Pouya-moh/urdf-to-kdl#2]
i was able to generate the executable using cmake and make.
I am little confused on how will the output from the executable  for given urdf will be used in KDL chain for e.g. something like this?

********************

        Chain kdlChain = Chain();

	Joint joint1(Joint::None);
	Frame frame1 = Frame(Rotation::EulerZYX(0.0, 0.0, -M_PI / 2))*Frame(Vector(0.0, 150.0, 0.0));
	kdlChain.addSegment(Segment(joint1, frame1));

********************

what i got was
-  Segment base has 1 children
    - Segment link_0 has 1 children
        - ....

there is no info about joint that i can use from the output of the executable.

if you can share how I can get joint information from urdf that would be helpful.

Thank you.

**Comment by Pouya-moh** [comment]
Hi,

I'm not sure I got your point tbh. `urdf-to-kdl` creates a KDL tree or chain which then you can use to create (e.g.,) Jacobian or inverse dynamic solvers. The output that you see is simply a walk through a text kinematic chain. 

The example file in [test](https://github.com/Pouya-moh/urdf-to-kdl/blob/master/test/check_kdl_parser.cpp) may help you a bit. Alternatively look to ROS documentation where is the source of `urdf-to-kdl`.

Cheers!
